### ISSUE TITLE
crash on 3rd activity upload

### ISSUE THREAD

**Issue by ejbruce** [CSAIL-LivingLab/getfit#13]
Deleted and reinstalled latest getfit app.  Successfully logged 2 activities.  On 3rd activity, when I hit save I got a message that could not save to getfit (not a team member) and then exited app.  Reopened and logged a 4th activity, and it successfully saved.

**Comment by RogerTangos** [comment]
Hey Elizabeth - when the app crashed, did iOS close the app, or did it give you an error message, and then continue? I'm curious to know what the error message was.

**Comment by ejbruce** [comment]
I got an error msg that said something about not having access to 
getfit, not a member of the team, and then app closed/exited

If I get it again, I will try and capture the error msg

On 1/28/15, 4:12 PM, Albert Carter wrote:

> Hey Elizabeth - when the app crashed, did iOS close the app, or did it 
> give you an error message, and then continue? I'm curious to know what 
> the error message was.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/CSAIL-LivingLab/getfit/issues/13#issuecomment-71916995.

## 

Elizabeth J. Bruce
Executive Director, MIT Big Data Initiative at CSAIL
Massachusetts Institute of Technology
w. 617.258.9702
c. 617.513.3362
http://bigdata.csail.mit.edu/

**Comment by RogerTangos** [comment]
Was it possibly this one?

"Your minutes were not saved. Please make sure that you have filled out your getfit profile http://getfit.mit.edu/profile"

**Comment by ejbruce** [comment]
no - I remember it saying somethin gabout not being on a team....

On 1/28/15, 4:34 PM, Albert Carter wrote:

> Was it possibly this one?
> 
> "Your minutes were not saved. Please make sure that you have filled 
> out your getfit profile http://getfit.mit.edu/profile"
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/CSAIL-LivingLab/getfit/issues/13#issuecomment-71920919.

## 

Elizabeth J. Bruce
Executive Director, MIT Big Data Initiative at CSAIL
Massachusetts Institute of Technology
w. 617.258.9702
c. 617.513.3362
http://bigdata.csail.mit.edu/

**Comment by RogerTangos** [comment]
This is happening because GetFit sometimes redirects to /dashboard and other times loads /minutes. We're not sure why.

The app currently assumes /dashboard, but to check for /mintues. The formIds on the /minutes page is below:
"search_block_form"
"getfit_minutes_select_week_form"
"getfit_minutes_add_form_1"
"getfit_minutes_del_form_1_1"
"getfit_minutes_del_form_1_2"
"getfit_minutes_add_form_2"
"getfit_minutes_add_form_3"
"getfit_minutes_del_form_3_1"
"getfit_minutes_del_form_3_2"
"getfit_minutes_add_form_4"
"getfit_minutes_del_form_4_1"
"getfit_minutes_add_form_5"
"getfit_minutes_add_form_6"
"getfit_minutes_add_form_7"

This will require a JS update of the token scraping code.

**Comment by RogerTangos** [comment]
Closed with 7ef5c83978ff0a3b11cbbfb7d3d42fb1f00d6d06, and 

https://github.com/CSAIL-LivingLab/getfit-html
c9457ea753895f409e23438312d54d606e615b61
