### ISSUE TITLE
crash on intro

### ISSUE THREAD

**Issue by ejbruce** [CSAIL-LivingLab/getfit#9]
I deleted and reinstalled app, on second welcome screen it crashed and exited app

**Comment by RogerTangos** [comment]
Thanks for logging this on github! I'll look into it tomorrow.

**Comment by RogerTangos** [comment]
I managed to recreate this on the iPhone 5s iOS 7.1 simulator. It's related to the fact that the app uses a UIPageViewController to move from introAboutVC to introDetailVC.

Interestingly, this doesn't happen on other simulators.

2015-01-28 18:04:13.363 GetFit[13102:60b] **\* Terminating app due to uncaught exception 'NSRangeException', reason: '**\* -[__NSArrayI objectAtIndex:]: index 9223372036854775806 beyond bounds [0 .. 0]'
**\* First throw call stack:
(
    0   CoreFoundation                      0x000000010a41e495 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010a17999e objc_exception_throw + 43
    2   CoreFoundation                      0x000000010a3d6e3f -[__NSArrayI objectAtIndex:] + 175
    3   GetFit                              0x0000000107f7567d -[IntroPageVC pageViewController:viewControllerBeforeViewController:] + 189
    4   UIKit                               0x0000000108fced60 -[UIPageViewController _queuingScrollView:viewBefore:view:] + 129

**Comment by RogerTangos** [comment]
Resolved in a4bd2031b1c6b51d7c8085812ed38f95fd315c95. Introduces minor bug #18.
